config/routes.rb
Expert::Application.routes.draw do
  resources :questions
  resources :partners

  devise_for :users, :skip => :registrations

  resources :feedbacks, :only => [:new, :create]

  def metaitems
    resource :metaitems, :only => [:edit, :update]
  end
  
  resources :locations, :only => [:edit, :update]

  resources :newsposts do 
    metaitems
  end

  resources :articles do
    metaitems
  end

  root :to => 'articles#index'
 

end

app/models/metaitem.rb
class Metaitem < ActiveRecord::Base
  belongs_to :page, :polymorphic => true
end

app/controllers/metaitems_controller.rb
class MetaitemsController < ApplicationController
  before_filter :find_resource
  
  def edit
    if @resource.metaitem.present?
      @metaitem = @resource.metaitem
    else
      @metaitem = @resource.build_metaitem
    end
  end

  def update
    if @resource.metaitem.present?
      @metaitem = @resource.metaitem
      @metaitem.attributes = params[:metaitem]
    else
      @metaitem = @resource.build_metaitem(params[:metaitem])
    end

    if @metaitem.save
      flash[:notice] = "All done"
    else
      flash[:alert] = "Error"
    end

    redirect_to polymorphic_path(@resource)
  end

private

  def find_resource
    @resource_name  = request.fullpath.split('/')[1].classify.downcase
    param_id        = @resource_name + "_id"
    @resource_klass = Kernel.const_get(@resource_name.classify)

    @resource = @resource_klass.send(:find, params[param_id])
  end
end

app/helpers/metaitems_helper.rb
module MetaitemsHelper
end

app/views/metaitems/_form.html.erb
<%= form_for [@resource, @metaitem], :url => polymorphic_path([@resource, @metaitem]), :method => :put, :html=>{:class=>'editor_form'} do |f| %>
  <% if @metaitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metaitem.errors.count, "error") %> prohibited this metaitem from being saved:</h2>

      <ul>
      <% @metaitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_area :keywords %>
  </div>
  <div class="actions">
    <%= f.submit 'Сохранить' %>
  </div>
<% end %>

app/views/metaitems/edit.html.erb
<div id="content">
<h1>Редактор метаданных</h1>

<%= render 'form' %>

<%= link_to 'Обратно', polymorphic_path(@resource) %>
</div>

app/views/metaitems/index.html.erb
<h1>Listing metaitems</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Keywords</th>
    <th>Page</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @metaitems.each do |metaitem| %>
  <tr>
    <td><%= metaitem.title %></td>
    <td><%= metaitem.description %></td>
    <td><%= metaitem.keywords %></td>
    <td><%= metaitem.page %></td>
    <td><%= link_to 'Show', metaitem %></td>
    <td><%= link_to 'Edit', edit_metaitem_path(metaitem) %></td>
    <td><%= link_to 'Destroy', metaitem, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Metaitem', new_metaitem_path %>

app/views/metaitems/new.html.erb
<div id="content">
<h1>Новые метаданные</h1>

<%= render 'form' %>

<%= link_to 'Обратно', metaitems_path %>
</div>

app/views/metaitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @metaitem.title %>
</p>

<p>
  <b>Description:</b>
  <%= @metaitem.description %>
</p>

<p>
  <b>Keywords:</b>
  <%= @metaitem.keywords %>
</p>

<p>
  <b>Page:</b>
  <%= @metaitem.page %>
</p>


<%= link_to 'Edit', edit_metaitem_path(@metaitem) %> |
<%= link_to 'Back', metaitems_path %>