config/routes.rb
Expert::Application.routes.draw do
  resources :questions
  resources :partners

  devise_for :users, :skip => :registrations

  resources :feedbacks, :only => [:new, :create]

  def metaitems
    resource :metaitems, :only => [:edit, :update]
  end
  
  resources :locations, :only => [:edit, :update]

  resources :newsposts do 
    metaitems
  end

  resources :articles do
    metaitems
  end

  root :to => 'articles#index'
 

end

app/views/shared/_sub_menu.html.erb
 <div id="secondary-menu">
        <% if article.slogan %>
          <h2 class="page-title"><%= article.slogan %></h2>
        <%end%>
       
        <% childs = Article.where(:parent_id => article.id)%>
        <% left_column = childs[0..7] %>
        <% right_column = childs[8..childs.length-1] %>
       
        <% if left_column %>
          <ul class="menu">            
            <% left_column.each do |article|%>
               <li><%= link_to article.name, article_path(article)%></li>
            <% end %>
          </ul>
        <% end %>

        <% if right_column %>
         <ul class="menu shifted">
            <% right_column.each do |article|%>
               <li><%= link_to article.name, article_path(article) %></li>
            <% end %>
         </ul>
        <% end %>

        <div class="bg1"></div>

        <% image = sub_menu_image (article) %> 
        
        <% if image %>
          <%= content_tag :div, {:class =>'bg2',:style =>"background: url('#{image.thumb('554x245#').url}')"} do end%>
        <% else %>
           <%= content_tag :div,{ :class =>'bg2'} do end%>
        <% end %>
                
 <%# image = article.addon.present? ? sub_menu_image_for_addon(article.addon) : sub_menu_image(article) %>

 <%#= render :partial => '/shared/sub_menu_image', :locals => {:image => sub_menu_image(article) } %>
       
   </div>

app/views/shared/_sub_menu_image.html.erb
   
        <% if image %>
            <%= content_tag :div, {:class =>'bg2',:style =>"background: url('#{image.url}')"} do end%>
        <% else %>
             <%= content_tag :div,{ :class =>'bg2'} do end%>
        <% end %>

app/views/shared/_tinymce.html.erb
<script type="text/javascript">
    tinyMCE.init({
            mode : "textareas",
            theme : "advanced",
            plugins : "advhr",
            //editor_selector : "mceEditor",
            //editor_deselector : "mceNoEditor",


            // Theme options - button# indicated the row# only
            theme_advanced_buttons1 : "bold,italic,underline,|,justifyleft,justifycenter,justifyright,fontsizeselect,formatselect,|,bullist,numlist,|,outdent,indent,|,link,unlink,|,code,|,removeformat,|,sub,sup",
            theme_advanced_buttons2 : "",
            theme_advanced_buttons3 : "",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true
    });
</script>

app/views/shared/_tool_bar.html.erb
 <div id="toolbar">
       <ul>
           <li><%= link_to "Добавить раздел", new_article_path %></li>
           
           <%if @article.present? %>
             <li><%= link_to "Изменить раздел", edit_article_path(@article) %></li>
             <li>
              <%= link_to "Удалить раздел", @article, confirm: 'Вы уверены?', method: :delete %>
             </li>           
          
             
           <% if @article.addon.present? %>
             <li><%= addon_new_link(@article.addon) %></li>  
           <%end%>

            
          
           
            <% concat content_tag :li, (link_to 'Метаданные раздела',
                 edit_article_metaitems_path(@article)) if @newspost.blank? %>
          
         

           <%end%>

            <%if @newspost.present?%>
             <li>
               <%= link_to 'Метаданные новости', edit_newspost_metaitems_path(@newspost) %>
             </li>
            <%end%>



           <li><%= link_to "Настройки", edit_location_path(:id=>1) %></li>
           <li><%= link_to "Выход", destroy_user_session_path %></li>
       </ul>
  </div>