config/routes.rb
Expert::Application.routes.draw do
  resources :questions
  resources :partners

  devise_for :users, :skip => :registrations

  resources :feedbacks, :only => [:new, :create]

  def metaitems
    resource :metaitems, :only => [:edit, :update]
  end
  
  resources :locations, :only => [:edit, :update]

  resources :newsposts do 
    metaitems
  end

  resources :articles do
    metaitems
  end

  root :to => 'articles#index'
 

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	validates :name, :email, :message, :presence => true
	validates :name, :title, :length => {:maximum => 250}
	validates :email, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
end

app/controllers/feedbacks_controller.rb
# encoding: UTF-8
class FeedbacksController < ApplicationController
 before_filter :find_article
 skip_before_filter :authenticate_user!
 def new
    @feedback = Feedback.new

  end

  def create
    @feedback = Feedback.new(params[:feedback])
    flash[:notice]=nil
    
    if (@feedback.valid? and human?)
	    if (Messager.to_admin(@feedback).deliver and Messager.to_guest(@feedback).deliver)
    	  flash[:notice] = 'Письмо успешно отправлено'
    	else
          flash[:alert] = 'Не удалось отправить письмо'
        end 
      @feedback =Feedback.new       
    	render action:'new'
    else
    	flash[:alert] = 'Поля формы заполнены не верно'
    	render action:'new'
    end
       
   
  end
  def find_article
    @article = Article.where(:addon=>'feedback').first
  end
  def human?
    return true if @feedback.spam.blank? 
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit 'Отправить' %>
  </div>

<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Title</th>
    <th>Message</th>
    <th>Spam</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.name %></td>
    <td><%= feedback.email %></td>
    <td><%= feedback.title %></td>
    <td><%= feedback.message %></td>
    <td><%= feedback.spam %></td>
    <td><%= link_to 'Show', feedback %></td>
    <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
    <td><%= link_to 'Destroy', feedback, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<% parse_metadata @article %>

<%= render_sub_menu @article %>
<div id="content">
<%= content_tag :h1, @article.head if @article.head.present? %>
<%= content_tag :p, @article.body if @article.body.present? %>
<p class="tip"><%= notice.blank? ? alert : notice%></p>
<%= render 'form' %>
</div>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @feedback.name %>
</p>

<p>
  <b>Email:</b>
  <%= @feedback.email %>
</p>

<p>
  <b>Title:</b>
  <%= @feedback.title %>
</p>

<p>
  <b>Message:</b>
  <%= @feedback.message %>
</p>

<p>
  <b>Spam:</b>
  <%= @feedback.spam %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>